### ISSUE TITLE
Fails to find correct git_worktree_root

### ISSUE THREAD

**Issue by TamaMcGlinn** [ThePrimeagen/git-worktree.nvim#34]
I open vim in my home directory, then change the directory to that of a git worktree within a bare repository. Then I try to switch to a different worktree, but git-worktree falls back to the `:Explore` command because it can't find the file - after adding some debugging print statements in init.lua I find that it is trying to find it inside my home directory, because `local git_worktree_root = vim.loop.cwd()` is called when the plugin is loaded.

**Comment by ThePrimeagen** [comment]
was this addressed by #29 ?

I feel like you mentioned this.

**Comment by TamaMcGlinn** [comment]
No. And I just updated but that made things worse. Now it doesn't work even if I start vim in the bare git repo directory, because now git_worktree_root is nil rather than the directory which vim starts in.

**Comment by TamaMcGlinn** [comment]
Sorry for the duplicate issue; I did not find #29 but this is exactly that issue. It's just not solved yet.

**Comment by polarmutex** [comment]
I am confused , is this solved or is there an issue on the latest master now?  the latest master is detecting the git root on my system just want to make sure I did not miss a corner case.

**Comment by ThePrimeagen** [comment]
I may also be missing something.

My testing I can create, delete, and switch trees as of now.  I use bare repos.

**Comment by ThePrimeagen** [comment]
Should we also move this convo to #29?

**Comment by TamaMcGlinn** [comment]
I'm not sure where to move this either; I was thinking #30 at first, since it was the same issue, but then I updated to the latest master (cdcc26d  Merge pull request #32 from rudotriton/prompt-title) and now switching doesn't work even if I do start vim in the git root directory. So I guess this really is a new issue, and I will reopen.

I would love to add a failing unit test in a PR, but I don't understand how to even the unit tests at all; you require("git-worktree") and I guess that *should* read git-worktree/init.lua but my lua installation just says it can't find git-worktree.lua in various directories.

I will keep debugging this, but in terms of repro steps it's as simple as 'try to change worktrees' using `:lua require('telescope').extensions.git_worktree.git_worktrees()`, so it is a mystery to me why I am the only one with the problem.

**Comment by TamaMcGlinn** [comment]
I've temporarily fixed this in my own vimrc with this:

```
fu! Switch_Worktree() abort
  lua require('git-worktree')._find_git_root_job()
  lua require('telescope').extensions.git_worktree.git_worktrees()
endfunction

nnoremap <leader>gww :call Switch_Worktree()<CR>
```

You are still assuming that the directory which vim initially starts in is within the git project; I tend to start nvim straight in my home directory, and have a Startify menu which means one number press brings me into both file and directory of one of the last places I was editing before. I also change directory all the time when moving about from project to project, so it doesn't make sense to me to call find_git_root_job() once at startup and then never again.

**Comment by TamaMcGlinn** [comment]
I also noticed that when you have 3 worktrees involved, where one is the current CD path, you have a file open which is in the second, but you want to switch to a third one, then `git_worktrees()` manages to switch the directory, but is not able to open the file afterwards, so it opens the root directory instead. Really the current directory should not be relevant; rather than doing a string substitution to get the relative path from the root of the worktree to the file, we should probably just ask git: `!git rev-parse --show-prefix %` ?

**Comment by polarmutex** [comment]
I see the issue now, calling any of the functions requires you to be in a git repo. with #37 , I want to discuss and think about the best way to add this in. For example, if we use just branch names, we will have no way to know the git repo unless the cwd was a the git repo we want to use.

for what is currently implemented(using path not branch)  will the following be good?

For Switch and Delete
- If the current cwd is a git repo, any call should use that directory
- If the current cwd is not a git repo, check the path is in a git repo and use that if so
For Create
- Always assume we are in a git repo

Then to support #37, we could create new functions that take a branch name and require to be in a git repo

Thoughts?

**Comment by TamaMcGlinn** [comment]
I don't believe the current working directory is ever relevant, and I certainly wouldn't want it to influence the decision of where to jump to. For instance, fugitive also only looks at the actual file you have open, and completely ignores your working directory.

Is it acceptable to add a dependency on the fugitive plugin?

```
let root_dir = system(fugitive#repo().git_command() . ' rev-parse --git-dir')
```

Otherwise, grabbing the internals of fugitive would also be more efficient that this; that system call is not necessary since fugitive already knows for each buffer what the git-dir is.

**Comment by polarmutex** [comment]
changed so it finds the git root when calling create. switch, or delete.

**Comment by ThePrimeagen** [comment]
There is a danger when considering the current file.  Which in some sense I would argue is wrong.

You could end up changing all sorts of things like that.  

Perhaps this is a mode of operation issue.  I will never open up files all around, I'll just be switching worktrees as I do my work.  I always open my vim experience from the root, and the starting place, the cwd, is the git root at all times except when I shortcut and go to the branch I really want (which btw still works).

The reason why I don't like only considering current file is that I sometimes edit my vimrc.  That is in completely different project and I wont want it to influence anything.

@TamaMcGlinn I think that a unit test showing the break would be the best possible solution to this.  If you make a PR with a breaking unit test I am positive I or polar can have a more robust talk about this because I ma still slightly confused of the exact use case you are going for (even when reading it).  I know, I am big dumb, and want to support you :)

**Comment by matu3ba** [comment]
@TamaMcGlinn Your best bet is to use telescope-project and provide a commit to [shell out the check if `:lcd` switched to a worktree](https://stackoverflow.com/a/15802301) and setting it accordingly via script inside git-worktree.

Unfortunately telescope-project has no support for checking if a path is a bare git yet, but it should work nevertheless.

**Comment by ThePrimeagen** [comment]
Sorry, I've just been so busy to try to take care of these things. I'll try to take a look at it this week. But I can feel that nfts are going to creep up and take all my time.
